# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0016_auto_20171114_2046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='Номинал')),
                ('year', models.CharField(blank=True, max_length=64, verbose_name='Год на монете')),
                ('specific', models.CharField(blank=True, max_length=255, verbose_name='Особенности')),
                ('inuse', models.BooleanField(default=False, verbose_name='Хождение')),
                ('haveit', models.BooleanField(default=True, verbose_name='В коллекции')),
                ('special', models.BooleanField(default=False, verbose_name='Памятная')),
                ('sell', models.BooleanField(default=False, verbose_name='Продажа/обмен')),
                ('condition', models.CharField(blank=True, choices=[('MN', 'Отличное'), ('VG', 'Хорошее'), ('MD', 'Среднее'), ('BD', 'Плохое')], default='VG', max_length=2, verbose_name='Состояние')),
                ('avers', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Аверс')),
                ('revers', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Реверс')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарии')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Country', verbose_name='Страна')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Купюры',
                'verbose_name': 'Купюра',
            },
        ),
        migrations.AddIndex(
            model_name='bone',
            index=models.Index(fields=['year', 'value'], name='bones_bone_year_4a1c01_idx'),
        ),
    ]
