# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CN', 'Монеты'), ('BN', 'Купюры'), ('MD', 'Карты'), ('BD', 'Плохое')], default='CN', max_length=2, verbose_name='Тип')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('public', models.BooleanField(default=True, verbose_name='Показывать')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
