# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_auto_20171111_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='cname',
            new_name='name',
        ),
    ]
